# ===== Minimal, professional Academic Pages config for Vikas Shah =====
# Keep things lean; only relevant sections enabled.
# Site
title: "Vikas Shah"
description: "Software Development Engineer — Django, FastAPI, React, AWS, Kafka. Hardware integration & video analytics."
url: "https://vikasshah8218.github.io"
baseurl: ""

timezone: "Asia/Kolkata"
locale: "en-US"

# Theme
remote_theme: "academicpages/academicpages"
minimal_mistakes_skin: "default"
highlighter: "rouge"
markdown: "kramdown"
kramdown:
  input: GFM
  hard_wrap: false
sass:
  style: compressed

# Plugins (lean set)
plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Author block used by Minimal Mistakes/AcademicPages
author:
  name: "Vikas Shah"
  avatar: "/images/profile.jpg"   # replace with your photo if different
  bio: >-
    SDE with 2+ years’ experience building ERP, VMS, Access Control & ANPR systems.
    Focus on backend, microservices, and device integrations (Moxa, Adam, HID, IP cameras) with
    Django/FastAPI/React on AWS, Kafka/Redis/Celery, and CI/CD. Scaled apps to 5K+ daily sessions,
    improved response times by ~30%, and optimized video analytics & ANPR pipelines.
  location: "India"
  email: "Vikasshah8218@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/VikasShah8218"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/mr-vikas-shah-248586253/"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:Vikasshah8218@gmail.com"
    - label: "Resume (PDF)"
      icon: "fas fa-file-pdf"
      url: "/files/Mr%20Shah%20Resume.pdf"

# Social usernames for SEO
github_username: "VikasShah8218"
linkedin_username: "mr-vikas-shah-248586253"

# Analytics (leave blank if not used)
google_analytics: ""

# Permalinks
permalink: "/:categories/:title/"
paginate: 5
paginate_path: "/page:num/"

# Collections — only what you need
collections:
  posts:
    output: true
    permalink: /posts/:title/
  portfolio:
    output: true
    permalink: /portfolio/:title/

# Disable unused academic sections by not declaring them:
# publications, talks, teaching (folders may exist but won't render if not listed above)

# Navigation (top menu)
# Ensure the pages below exist in _pages/ or adjust to your structure.
nav:
  - title: "About"
    url: /about/
  - title: "Projects"
    url: /portfolio/
  - title: "Blog"
    url: /posts/
  - title: "Resume"
    url: /files/Mr%20Shah%20Resume.pdf

# Defaults (applies author info to posts and portfolio items)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: "single"
      author_profile: true

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/VikasShah8218"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/mr-vikas-shah-248586253/"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:Vikasshah8218@gmail.com"
